"""Mirror selected Affinity developer-site pages (versioning + changelogs) as markdown."""
from __future__ import annotations

from dataclasses import dataclass
import re

import requests

SITE_BASE = "https://developer.affinity.co"


@dataclass(frozen=True)
class SitePage:
    site_path: str  # e.g. "pages/external-api-v2/versioning"
    output_name: str  # file name under the pages directory
    title: str  # expected H1 on the live page

    @property
    def markdown_url(self) -> str:
        return f"{SITE_BASE}/{self.site_path}.md"

    @property
    def html_url(self) -> str:
        return f"{SITE_BASE}/{self.site_path}"


PAGES: tuple[SitePage, ...] = (
    SitePage("pages/external-api-v2/versioning", "versioning.md", "Versioning"),
    SitePage("pages/changelog/previous-changes", "previous-changes.md", "Previous Changes"),
    SitePage("pages/changelog/version-migration", "version-migration.md", "Version Migration"),
)

# Full site path (without ".md") -> mirrored sibling file. Matched on the full path, never the
# basename: "/pages/data-share/versioning" is a different page from our versioning.md.
MIRRORED_PATHS = {f"/{page.site_path}": page.output_name for page in PAGES}

_LINK_RE = re.compile(r"\]\((/[^)\s]*)\)")
_FENCE_RE = re.compile(r"^(\s*```+[\w+-]*)\s+theme=\{[^}]*\}\s*$")


class PageFetchError(RuntimeError):
    """Raised when a page cannot be fetched or does not look like the expected markdown."""


def fetch_page(page: SitePage, timeout: int = 30) -> str:
    """Fetch the raw markdown for a page, refusing error pages and HTML."""
    try:
        response = requests.get(page.markdown_url, timeout=timeout)
        response.raise_for_status()
    except requests.RequestException as exc:
        raise PageFetchError(f"{page.markdown_url}: {exc}") from exc
    content_type = response.headers.get("Content-Type", "").split(";")[0].strip().lower()
    if content_type != "text/markdown":
        raise PageFetchError(f"{page.markdown_url}: unexpected content-type {content_type!r}")
    text = response.text
    if text.lstrip().startswith("<") or "<!DOCTYPE" in text[:2000]:
        raise PageFetchError(f"{page.markdown_url}: response looks like HTML")
    if not re.search(rf"^# {re.escape(page.title)}\s*$", text, flags=re.MULTILINE):
        raise PageFetchError(f"{page.markdown_url}: expected heading '# {page.title}' not found")
    return text


def _rewrite_link(target: str) -> str:
    path, sep, fragment = target.partition("#")
    if path.endswith(".md"):
        path = path[: -len(".md")]
    suffix = f"#{fragment}" if sep else ""
    if path in MIRRORED_PATHS:
        return f"{MIRRORED_PATHS[path]}{suffix}"
    return f"{SITE_BASE}{path}{suffix}"


def normalize_page(text: str) -> str:
    """Strip Mintlify boilerplate, rewrite site-relative links, and normalize whitespace."""
    lines = text.replace("\r\n", "\n").split("\n")

    # Leading "> ## Documentation Index ..." preamble block.
    if lines and lines[0].startswith(">") and "Documentation Index" in lines[0]:
        while lines and lines[0].startswith(">"):
            lines.pop(0)

    # "Related topics" is generated by Mintlify and is followed by the platform footer.
    for idx, line in enumerate(lines):
        if line.strip() == "## Related topics":
            lines = lines[:idx]
            break
    else:
        lines = [line for line in lines if "built and hosted on [Mintlify]" not in line]

    normalized: list[str] = []
    for line in lines:
        line = _FENCE_RE.sub(r"\1", line)
        line = _LINK_RE.sub(lambda m: f"]({_rewrite_link(m.group(1))})", line)
        normalized.append(line.rstrip())
    body = "\n".join(normalized).strip("\n")
    body = re.sub(r"\n{3,}", "\n\n", body)
    body = re.sub(r"(\n\s*\*{3,}\s*)+$", "", body)  # trailing horizontal rule left by the footer
    return body.strip() + "\n"


def render_page(page: SitePage, body: str) -> str:
    """Prepend the generated-file header. No timestamp, so files only change with upstream content."""
    header = "\n".join(
        [
            "<!-- AUTO-GENERATED by tools/v2_sync_pipeline/sync_v2_docs.py. Do not edit. -->",
            "",
            f"> **Unofficial copy** of [{page.title}]({page.html_url}) from Affinity's developer site, "
            "mirrored automatically. The official page is authoritative.",
            "",
        ]
    )
    return f"{header}\n{body}"
